name: Create an issue
description: |
  This action implements `POST` request to `/repos/{owner}/{repo}/issues`

inputs:
  token:
    description: |
      Token to authenticate the request
    required: true
  owner:
    description: |
      owner parameter
    required: true
  repo:
    description: |
      repo parameter
    required: true
  title:
    description: |
      The title of the issue.
    required: true
  body:
    description: |
      The contents of the issue.
    required: false
  assignee:
    description: |
      Login for the user that this issue should be assigned to. _NOTE: Only users with push access can set the assignee for new issues. The assignee is silently dropped otherwise. **This field is deprecated.**_
    required: false
  milestone:
    description: |
      The `number` of the milestone to associate this issue with. _NOTE: Only users with push access can set the milestone for new issues. The milestone is silently dropped otherwise._
    required: false
  labels:
    description: |
      Labels to associate with this issue. _NOTE: Only users with push access can set labels for new issues. Labels are silently dropped otherwise._
    required: false
  assignees:
    description: |
      Logins for Users to assign to this issue. _NOTE: Only users with push access can set assignees for new issues. Assignees are silently dropped otherwise._
    required: false

runs:
  using: node12
  main: index.js

