name: Reset an authorization
description: |
  **Deprecation Notice:** GitHub will replace and discontinue OAuth endpoints containing `access_token` in the path parameter. We are introducing new endpoints that allow you to securely manage tokens for OAuth Apps by using `access_token` as an input parameter. The OAuth Application API will be removed on July 1, 2020. For more information, including scheduled brownouts, see the [blog post](https://developer.github.com/changes/2020-02-14-deprecating-oauth-app-endpoint/).  OAuth applications can use this API method to reset a valid OAuth token without end-user involvement. Applications must save the "token" property in the response because changes take effect immediately. You must use [Basic Authentication](https://developer.github.com/v3/auth#basic-authentication) when accessing this endpoint, using the OAuth application's `client_id` and `client_secret` as the username and password. Invalid tokens will return `404 NOT FOUND`.

inputs:
  token:
    description: |
      Token to authenticate the request
    required: true
  client_id:
    description: |
      client_id parameter
    required: true
  access_token:
    description: |
      access_token parameter
    required: true
  file_output:
    description: |
      Path to store full output of the action
    required: false
  custom_outputs:
    description: |
      Custom outputs to create for step. This has to be YAML multiline string literal `custom_outputs: \|<newline> output_name:path.in.result`
    required: false

runs:
  using: node12
  main: index.js

