name: List comments on a pull request
description: |
  **Note:** Multi-line comments on pull requests are currently in public beta and subject to change.  Lists review comments for a pull request. By default, review comments are in ascending order by ID.  **Multi-line comment summary**  **Note:** New parameters and response fields are available for developers to preview. During the preview period, these response fields may change without advance notice. Please see the [blog post](https://developer.github.com/changes/2019-10-03-multi-line-comments) for full details.  Use the `comfort-fade` preview header and the `line` parameter to show multi-line comment-supported fields in the response.  If you use the `comfort-fade` preview header, your response will show:  *   For multi-line comments, values for `start_line`, `original_start_line`, `start_side`, `line`, `original_line`, and `side`. *   For single-line comments, values for `line`, `original_line`, and `side` and a `null` value for `start_line`, `original_start_line`, and `start_side`.  If you don't use the `comfort-fade` preview header, multi-line and single-line comments will appear the same way in the response with a single `position` attribute. Your response will show:  *   For multi-line comments, the last line of the comment range for the `position` attribute. *   For single-line comments, the diff-positioned way of referencing comments for the `position` attribute. For more information, see `position` in the [input parameters](https://developer.github.com/v3/pulls/comments/#parameters-2) table.  The `reactions` key will have the following payload where `url` can be used to construct the API location for [listing and creating](https://developer.github.com/v3/reactions) reactions.  

inputs:
  token:
    description: |
      Token to authenticate the request
    required: true
  owner:
    description: |
      owner parameter
    required: false
  repo:
    description: |
      repo parameter
    required: false
  pull_number:
    description: |
      pull_number parameter
    required: true
  sort:
    description: |
      Can be either `created` or `updated` comments.
    required: true
  direction:
    description: |
      Can be either `asc` or `desc`. Ignored without `sort` parameter.
    required: true
  since:
    description: |
      This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`. Only returns comments `updated` at or after this time.
    required: true
  per_page:
    description: |
      Results per page (max 100)
    required: true
  page:
    description: |
      Page number of the results to fetch.
    required: true

runs:
  using: node12
  main: index.js

