name: List project cards
description: |
  This action implements `GET` request to `/projects/columns/{column_id}/cards`

inputs:
  token:
    description: |
      Token to authenticate the request
    required: true
  column_id:
    description: |
      column_id parameter
    required: true
  archived_state:
    description: |
      Filters the project cards that are returned by the card's state. Can be one of `all`,`archived`, or `not_archived`.
    required: true
  per_page:
    description: |
      Results per page (max 100)
    required: true
  page:
    description: |
      Page number of the results to fetch.
    required: true

runs:
  using: node12
  main: index.js

